/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBodyWeightsRouteImport } from './routes/admin/body-weights'
import { Route as AdminExercisesRouteImport } from './routes/admin/exercises'
import { Route as AdminSplitsRouteImport } from './routes/admin/splits'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWorkoutsRouteImport } from './routes/admin/workouts'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppExercisesRouteImport } from './routes/app/exercises'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppSplitsRouteImport } from './routes/app/splits'
import { Route as AppTrainRouteImport } from './routes/app/train'
import { Route as AppWeightRouteImport } from './routes/app/weight'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppHistoryIdRouteImport } from './routes/app/history.$id'
import { Route as AppSplitsIdRouteImport } from './routes/app/splits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBodyWeightsRoute = AdminBodyWeightsRouteImport.update({
  id: '/body-weights',
  path: '/body-weights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplitsRoute = AdminSplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkoutsRoute = AdminWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitsRoute = AppSplitsRouteImport.update({
  id: '/splits',
  path: '/splits',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainRoute = AppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AppRoute,
} as any)
const AppWeightRoute = AppWeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryIdRoute = AppHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppSplitsIdRoute = AppSplitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSplitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/body-weights': typeof AdminBodyWeightsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/splits': typeof AdminSplitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/api/$': typeof ApiSplatRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/progress': typeof AppProgressRoute
  '/app/splits': typeof AppSplitsRouteWithChildren
  '/app/train': typeof AppTrainRoute
  '/app/weight': typeof AppWeightRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/splits/$id': typeof AppSplitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/body-weights': typeof AdminBodyWeightsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/splits': typeof AdminSplitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/api/$': typeof ApiSplatRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/progress': typeof AppProgressRoute
  '/app/splits': typeof AppSplitsRouteWithChildren
  '/app/train': typeof AppTrainRoute
  '/app/weight': typeof AppWeightRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/splits/$id': typeof AppSplitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/body-weights': typeof AdminBodyWeightsRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/splits': typeof AdminSplitsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/workouts': typeof AdminWorkoutsRoute
  '/api/$': typeof ApiSplatRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/history': typeof AppHistoryRouteWithChildren
  '/app/progress': typeof AppProgressRoute
  '/app/splits': typeof AppSplitsRouteWithChildren
  '/app/train': typeof AppTrainRoute
  '/app/weight': typeof AppWeightRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/history/$id': typeof AppHistoryIdRoute
  '/app/splits/$id': typeof AppSplitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/body-weights'
    | '/admin/exercises'
    | '/admin/splits'
    | '/admin/users'
    | '/admin/workouts'
    | '/api/$'
    | '/app/exercises'
    | '/app/history'
    | '/app/progress'
    | '/app/splits'
    | '/app/train'
    | '/app/weight'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/app/'
    | '/app/history/$id'
    | '/app/splits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/body-weights'
    | '/admin/exercises'
    | '/admin/splits'
    | '/admin/users'
    | '/admin/workouts'
    | '/api/$'
    | '/app/exercises'
    | '/app/history'
    | '/app/progress'
    | '/app/splits'
    | '/app/train'
    | '/app/weight'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/app'
    | '/app/history/$id'
    | '/app/splits/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/body-weights'
    | '/admin/exercises'
    | '/admin/splits'
    | '/admin/users'
    | '/admin/workouts'
    | '/api/$'
    | '/app/exercises'
    | '/app/history'
    | '/app/progress'
    | '/app/splits'
    | '/app/train'
    | '/app/weight'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/app/'
    | '/app/history/$id'
    | '/app/splits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/body-weights': {
      id: '/admin/body-weights'
      path: '/body-weights'
      fullPath: '/admin/body-weights'
      preLoaderRoute: typeof AdminBodyWeightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/splits': {
      id: '/admin/splits'
      path: '/splits'
      fullPath: '/admin/splits'
      preLoaderRoute: typeof AdminSplitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workouts': {
      id: '/admin/workouts'
      path: '/workouts'
      fullPath: '/admin/workouts'
      preLoaderRoute: typeof AdminWorkoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/splits': {
      id: '/app/splits'
      path: '/splits'
      fullPath: '/app/splits'
      preLoaderRoute: typeof AppSplitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/train': {
      id: '/app/train'
      path: '/train'
      fullPath: '/app/train'
      preLoaderRoute: typeof AppTrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/weight': {
      id: '/app/weight'
      path: '/weight'
      fullPath: '/app/weight'
      preLoaderRoute: typeof AppWeightRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history/$id': {
      id: '/app/history/$id'
      path: '/$id'
      fullPath: '/app/history/$id'
      preLoaderRoute: typeof AppHistoryIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/app/splits/$id': {
      id: '/app/splits/$id'
      path: '/$id'
      fullPath: '/app/splits/$id'
      preLoaderRoute: typeof AppSplitsIdRouteImport
      parentRoute: typeof AppSplitsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBodyWeightsRoute: typeof AdminBodyWeightsRoute
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminSplitsRoute: typeof AdminSplitsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkoutsRoute: typeof AdminWorkoutsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBodyWeightsRoute: AdminBodyWeightsRoute,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminSplitsRoute: AdminSplitsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkoutsRoute: AdminWorkoutsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppHistoryRouteChildren {
  AppHistoryIdRoute: typeof AppHistoryIdRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryIdRoute: AppHistoryIdRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppSplitsRouteChildren {
  AppSplitsIdRoute: typeof AppSplitsIdRoute
}

const AppSplitsRouteChildren: AppSplitsRouteChildren = {
  AppSplitsIdRoute: AppSplitsIdRoute,
}

const AppSplitsRouteWithChildren = AppSplitsRoute._addFileChildren(
  AppSplitsRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppProgressRoute: typeof AppProgressRoute
  AppSplitsRoute: typeof AppSplitsRouteWithChildren
  AppTrainRoute: typeof AppTrainRoute
  AppWeightRoute: typeof AppWeightRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppProgressRoute: AppProgressRoute,
  AppSplitsRoute: AppSplitsRouteWithChildren,
  AppTrainRoute: AppTrainRoute,
  AppWeightRoute: AppWeightRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
